### ISSUE TITLE
Worth hosting releases in github for windows version?

### ISSUE THREAD

**Issue by DamonOehlman** [miniBloq/v0.83#4]
Notice that the dropbox link has been disabled due to high usage :(

**Comment by miniBloq** [comment]
Thanks! I will try to fix it. Regarding hosting in GitHub, I tried, but the file is too large and GH did not allow me to upload it.

**Comment by DamonOehlman** [comment]
No problem - thanks. I've just checked the github help and as far as I can tell you should be able to host the files no problem:

https://help.github.com/articles/about-releases/

I've never actually tried to host a large file through releases though...

**Comment by miniBloq** [comment]
Hi, I have uploaded it to the mirror provided by a friend from a Netherlands and the link is now the first one in http://blog.minibloq.org/p/download.html

I also kept the Dropbox one as a mirror, since it should be reactivated soon.

Regarding GitHub, I will love to host the production version here, but all the tries that I have done failed systematically.

Thanks again!

**Comment by DamonOehlman** [comment]
Thanks - managed to download the software fine now.  Shame that it doesn't upload to github - I wonder if it's worth hitting up their support to see if there is a reason why it isn't working and whether it can be resolved.
